---
os: linux
language: shell
dist: xenial
notifications:
  email: false

before_install: skip
install: skip

jobs:
  include:
    - stage: check
      name: 'Validate with shellcheck'
      script:
        - "git ls-files --exclude=\\*.sh --ignored | xargs shellcheck -e SC2015 -e SC2207"

