---
os: linux
language: shell
dist: xenial
notifications:
  email: false

before_install: skip
install: skip

jobs:
  include:
    ###  Testing on Travis CI is indefinitely disabled
    ###
    ###  See:
    ###    * https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
    ###    * https://simp-project.atlassian.net/browse/SIMP-8810
    ###
    ###
    ###    - stage: check
    ###      name: 'Validate with shellcheck'
    ###      script:
    ###        - "git ls-files --exclude=\\*.sh --ignored | xargs shellcheck -e SC2015 -e SC2207"

